version: '3'
services:
  redis:
    image: 'docker.io/redis:7.0.9-alpine'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /redis.conf
    volumes:
      - './redis/redis.conf:/redis.conf'
      - './redis/data:/data'
    container_name: pixelWarsRedis
<<<<<<< Updated upstream
  pixel-wars:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - './certs:/pixel-wars/backend/certs'
    container_name: pixelWarsBackend
=======
>>>>>>> Stashed changes
